apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "front-ui-service.fullname" . }}
  labels:
    {{- include "front-ui-service.labels" . | nindent 4 }}
data:
  # Generic key-value pairs from .Values.config
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}

  KEYCLOAK_ISSUER_URL: {{ .Values.config.keycloak_issuer_url | quote }}
  KEYCLOAK_SERVER_URL: {{ .Values.config.keycloak_server_url | quote }}