apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "customer-service.fullname" . }}
  labels:
    {{- include "customer-service.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{- if ne $key "database_url" }}
  {{ $key }}: {{ tpl ($value | toString) $ | quote }}
  {{- end }}
  {{- end }}

  SPRING_DATASOURCE_URL: {{ tpl .Values.config.database_url . | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.config.database_username | quote }}