# Global values (if any)
global:
  domain: prod.local # Example domain for ingress

# Configuration for the customer-service subchart
# NOTE: For local development (Minikube/Kind/Docker Desktop), build the image locally
# (e.g., `docker build -t customer-service:latest in customer-service dir)
# and ensure your K8s cluster can access local images (e.g., `minikube docker-env` or `kind load docker-image ...`).
customer-service:
  replicaCount: 1
  image:
    # --- REVERTED TO LOCAL REPO ---
    repository: customer-service # Removed registry prefix
    tag: "latest"
    pullPolicy: IfNotPresent # Use IfNotPresent for local images
    # -----------------------------
  service:
    type: ClusterIP
    port: 8081
  ingress:
    enabled: true
    className: "nginx" # Specify your ingress controller class
    hosts:
      - host: customer.prod.local # Use global domain or specific
        paths:
          - path: /
            pathType: ImplementationSpecific
  # Database connection details passed to customer-service configmap
  config:
    # --- CORRECTED DB URL --- Using '<ReleaseName>-<Alias>' service name convention
    database_url: "jdbc:postgresql://{{ .Release.Name }}-customer-db:5432/customerdb"
    # Secret reference for password is more secure
    database_username: "customer_user"
    # database_password_secret: "{{ .Release.Name }}-customer-db-postgresql" # Reference to secret created by DB chart
    # database_password_secret_key: "postgresql-password" # Key within the secret
    KEYCLOAK_ISSUER_URL: "http://keycloak.{{ .Release.Namespace }}.local/realms/bank-realm"
    DDL_AUTO_MODE: "update"
    KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"

fraud-service:
  replicaCount: 1
  image:
    repository: fraud-service
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8082
  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: fraud.prod.local
        paths:
          - path: /
            pathType: ImplementationSpecific
  config:
    database_url: "jdbc:postgresql://{{ .Release.Name }}-fraud-db:5432/frauddb"
    database_username: "fraud_user"
    # database_password_secret: "{{ .Release.Name }}-fraud-db-postgresql"
    # database_password_secret_key: "postgresql-password"

notification-service:
  replicaCount: 1
  image:
    repository: notification-service
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8083
  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: notification.prod.local
        paths:
          - path: /
            pathType: ImplementationSpecific
  config:
    database_url: "jdbc:postgresql://{{ .Release.Name }}-notification-db:5432/notificationdb"
    database_username: "notification_user"
    KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
    # database_password_secret: "{{ .Release.Name }}-notification-db-postgresql"
    # database_password_secret_key: "postgresql-password"

exchange-service:
  replicaCount: 1
  image:
    repository: exchange-service
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8086
  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: exchange.prod.local
        paths:
          - path: /
            pathType: ImplementationSpecific
  config:
    database_url: "jdbc:postgresql://{{ .Release.Name }}-exchange-db:5432/exchangedb"
    database_username: "exchange_user"
    DDL_AUTO_MODE: "update"
    # database_password_secret: "{{ .Release.Name }}-exchange-db-postgresql"
    # database_password_secret_key: "postgresql-password"

    KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"

exchange-generator-service:
  replicaCount: 1
  image:
    repository: exchange-generator-service
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8087
  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: exchange-generator.prod.local
        paths:
          - path: /
            pathType: ImplementationSpecific
  config:
    KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"

cash-service:
  replicaCount: 1
  image:
    repository: cash-service
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8088
  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: cash.myapp.local
        paths:
          - path: /
            pathType: ImplementationSpecific
  config:
    KEYCLOAK_ISSUER_URL: "http://keycloak.prod.local/realms/bank-realm"
    KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"

transfer-service:
  replicaCount: 1
  image:
    repository: transfer-service
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8089
  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: transfer.myapp.local
        paths:
          - path: /
            pathType: ImplementationSpecific
  config:
    KEYCLOAK_ISSUER_URL: "http://keycloak.prod.local/realms/bank-realm"
    KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"

front-ui-service:
  replicaCount: 1
  image:
    repository: front-ui-service
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8085
  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: front-ui.prod.local
        paths:
          - path: /
            pathType: ImplementationSpecific
  config:
    KEYCLOAK_ISSUER_URL: "http://keycloak.{{ .Release.Namespace }}.local/realms/bank-realm"
    KEYCLOAK_SERVER_URL: "http://keycloak.{{ .Release.Namespace }}.local"

keycloak:
  replicaCount: 1
  image:
    repository: quay.io/keycloak/keycloak
    tag: "26.1.3"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
      nginx.ingress.kubernetes.io/proxy-headers: "X-Forwarded-Proto, X-Forwarded-For"
    hosts:
      - host: keycloak.prod.local
        paths:
          - path: /
            pathType: ImplementationSpecific
  env:
    adminUser: admin
    adminPassword: admin

apigw-service:
  replicaCount: 1
  image:
    repository: apigw-service
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: apigw.prod.local
        paths:
          - path: /
            pathType: ImplementationSpecific
  config:
    KEYCLOAK_ISSUER_URL: "http://keycloak.{{ .Release.Namespace }}.local/realms/bank-realm"
    CUSTOMER_SERVICE_URL: "http://customer-service.{{ .Release.Namespace }}.svc.cluster.local:8081"
    FRONT_UI_SERVICE_URL: "http://front-ui-service.{{ .Release.Namespace }}.svc.cluster.local:8085"
    EXCHANGE_SERVICE_URL: "http://exchange-service.{{ .Release.Namespace }}.svc.cluster.local:8086"

# Configuration for the customer-db (PostgreSQL dependency)
# Values here are prefixed according to the Bitnami PostgreSQL chart's structure
# Check the Bitnami chart's values.yaml for all available options
customer-db:
  enabled: true
  # Override values from the official postgresql chart
  auth:
    database: customerdb
    username: customer_user
    # Use existingSecret or provide password (less secure for production)
    # existingSecret: "{{ .Release.Name }}-customer-db-postgresql" # Name of the secret to use/create
    password: "changeM3Customer!" # Example: Not recommended for production
  primary:
    persistence:
      enabled: true
      size: 1Gi # Small size for example

# Configuration for the exchange-db (PostgreSQL dependency)
exchange-db:
  enabled: true
  auth:
    database: exchangedb
    username: exchange_user
    # existingSecret: "{{ .Release.Name }}-exchange-db-postgresql"
    password: "changeM3Exchange!"
  primary:
    persistence:
      enabled: true
      size: 1Gi

kafka:
  enabled: true
  replicaCount: 1
  # === bitnamilegacy/kafka ===
  image:
    registry: docker.io
    repository: bitnamilegacy/kafka
    tag: "4.0.0-debian-12-r10"
    pullPolicy: IfNotPresent
  auth:
    interBrokerProtocol: "plaintext"
  listeners:
    client:
      protocol: "PLAINTEXT"
  kraft:
    enabled: true
  persistence:
    enabled: true
    size: 1Gi
