apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cash-service.fullname" . }}
  labels:
    {{- include "cash-service.labels" . | nindent 4 }}
data:
  # Generic key-value pairs from .Values.config
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}