apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "exchange-service.fullname" . }}
  labels:
    {{- include "exchange-service.labels" . | nindent 4 }}
data:
  # Process all config values with tpl to support Helm templating
  {{- range $key, $value := .Values.config }}
  {{ $key | upper }}: {{ tpl ($value | toString) $ | quote }}
  {{- end }}